---
current_progect_name: "{{ lookup('env','CI_PROJECT_NAME') }}"
backend_image: "{{ lookup('env','DOCKER_IMAGE') }}:{{ tag }}"
tag: "{{ lookup('env','CI_COMMIT_TAG') }}"
backend_contanner_name: "ct_{{ current_progect_name }}_{{ tag }}"
actual_commit: "{{ lookup('env','CI_COMMIT_SHORT_SHA') }}"
rate_bot_db_folder: "/opt/deploy/rate-posting-bot/"
rate_bot_db_volume_name: "rates_bot_volume"
